
package gov.vha.isaac.soap.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.12
 * Wed Jul 12 08:43:11 PDT 2017
 * Generated source version: 3.1.12
 */

@XmlRootElement(name = "ListMapEntriesFromSource", namespace = "urn:gov:va:med:sts:webservice:ct")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ListMapEntriesFromSource", namespace = "urn:gov:va:med:sts:webservice:ct", propOrder = {"MapSetVUID", "MapSetVersionName", "Sources", "SourceDesignationTypeName", "TargetDesignationTypeName", "PageSize", "PageNumber"})

public class ListMapEntriesFromSource {

    @XmlElement(name = "MapSetVUID")
    private java.lang.Long MapSetVUID;
    @XmlElement(name = "MapSetVersionName")
    private java.lang.String MapSetVersionName;
    @XmlElement(name = "Sources")
    private gov.vha.isaac.soap.transfer.SourcesTransfer Sources;
    @XmlElement(name = "SourceDesignationTypeName")
    private java.lang.String SourceDesignationTypeName;
    @XmlElement(name = "TargetDesignationTypeName")
    private java.lang.String TargetDesignationTypeName;
    @XmlElement(name = "PageSize")
    private java.lang.Integer PageSize;
    @XmlElement(name = "PageNumber")
    private java.lang.Integer PageNumber;

    public java.lang.Long getMapSetVUID() {
        return this.MapSetVUID;
    }

    public void setMapSetVUID(java.lang.Long newMapSetVUID)  {
        this.MapSetVUID = newMapSetVUID;
    }

    public java.lang.String getMapSetVersionName() {
        return this.MapSetVersionName;
    }

    public void setMapSetVersionName(java.lang.String newMapSetVersionName)  {
        this.MapSetVersionName = newMapSetVersionName;
    }

    public gov.vha.isaac.soap.transfer.SourcesTransfer getSources() {
        return this.Sources;
    }

    public void setSources(gov.vha.isaac.soap.transfer.SourcesTransfer newSources)  {
        this.Sources = newSources;
    }

    public java.lang.String getSourceDesignationTypeName() {
        return this.SourceDesignationTypeName;
    }

    public void setSourceDesignationTypeName(java.lang.String newSourceDesignationTypeName)  {
        this.SourceDesignationTypeName = newSourceDesignationTypeName;
    }

    public java.lang.String getTargetDesignationTypeName() {
        return this.TargetDesignationTypeName;
    }

    public void setTargetDesignationTypeName(java.lang.String newTargetDesignationTypeName)  {
        this.TargetDesignationTypeName = newTargetDesignationTypeName;
    }

    public java.lang.Integer getPageSize() {
        return this.PageSize;
    }

    public void setPageSize(java.lang.Integer newPageSize)  {
        this.PageSize = newPageSize;
    }

    public java.lang.Integer getPageNumber() {
        return this.PageNumber;
    }

    public void setPageNumber(java.lang.Integer newPageNumber)  {
        this.PageNumber = newPageNumber;
    }

}

