
package gov.vha.isaac.soap.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.12
 * Wed Jul 12 08:43:11 PDT 2017
 * Generated source version: 3.1.12
 */

@XmlRootElement(name = "ListValueSetContents", namespace = "urn:gov:va:med:sts:webservice:ct")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ListValueSetContents", namespace = "urn:gov:va:med:sts:webservice:ct", propOrder = {"VUID", "VersionName", "DesignationName", "MembershipStatus", "PageSize", "PageNumber"})

public class ListValueSetContents {

    @XmlElement(name = "VUID")
    private java.lang.Long VUID;
    @XmlElement(name = "VersionName")
    private java.lang.String VersionName;
    @XmlElement(name = "DesignationName")
    private java.lang.String DesignationName;
    @XmlElement(name = "MembershipStatus")
    private java.lang.String MembershipStatus;
    @XmlElement(name = "PageSize")
    private java.lang.Integer PageSize;
    @XmlElement(name = "PageNumber")
    private java.lang.Integer PageNumber;

    public java.lang.Long getVUID() {
        return this.VUID;
    }

    public void setVUID(java.lang.Long newVUID)  {
        this.VUID = newVUID;
    }

    public java.lang.String getVersionName() {
        return this.VersionName;
    }

    public void setVersionName(java.lang.String newVersionName)  {
        this.VersionName = newVersionName;
    }

    public java.lang.String getDesignationName() {
        return this.DesignationName;
    }

    public void setDesignationName(java.lang.String newDesignationName)  {
        this.DesignationName = newDesignationName;
    }

    public java.lang.String getMembershipStatus() {
        return this.MembershipStatus;
    }

    public void setMembershipStatus(java.lang.String newMembershipStatus)  {
        this.MembershipStatus = newMembershipStatus;
    }

    public java.lang.Integer getPageSize() {
        return this.PageSize;
    }

    public void setPageSize(java.lang.Integer newPageSize)  {
        this.PageSize = newPageSize;
    }

    public java.lang.Integer getPageNumber() {
        return this.PageNumber;
    }

    public void setPageNumber(java.lang.Integer newPageNumber)  {
        this.PageNumber = newPageNumber;
    }

}

