
package gov.vha.isaac.soap.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.12
 * Wed Jul 12 08:43:11 PDT 2017
 * Generated source version: 3.1.12
 */

@XmlRootElement(name = "ListMapEntriesFromSourceResponse", namespace = "urn:gov:va:med:sts:webservice:ct")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ListMapEntriesFromSourceResponse", namespace = "urn:gov:va:med:sts:webservice:ct")

public class ListMapEntriesFromSourceResponse {

    @XmlElement(name = "return")
    private gov.vha.isaac.soap.transfer.MapEntryValueListTransfer _return;

    public gov.vha.isaac.soap.transfer.MapEntryValueListTransfer getReturn() {
        return this._return;
    }

    public void setReturn(gov.vha.isaac.soap.transfer.MapEntryValueListTransfer new_return)  {
        this._return = new_return;
    }

}

