
package gov.vha.isaac.soap.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.12
 * Wed Jul 12 08:43:12 PDT 2017
 * Generated source version: 3.1.12
 */

@XmlRootElement(name = "SOAPException", namespace = "http://soap.xml.javax/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SOAPException", namespace = "http://soap.xml.javax/")

public class SOAPExceptionBean {

    private java.lang.String message;

    public java.lang.String getMessage() {
        return this.message;
    }

    public void setMessage(java.lang.String newMessage)  {
        this.message = newMessage;
    }

}

